### ISSUE TITLE
Problems with logo

### ISSUE THREAD

**Issue by tmazuryk** [Cores-ts/Fundingbox-support#4] opened 2016-01-21 20:44 UTC
Here logo showing: http://fundingbox.com/profiles/itaxi-pl (viewing profile)
and here not showing (broken image): http://fundingbox.com/profiles/bdfb72ef91ebb4009fef7980/success (editing profile)

In general logos are showing weird if not uploaded automatically.

For case of NetSprint a bit different issue with logo: http://fundingbox.com/profiles/netsprint-s-a-1
In profile viewing (showing): http://fundingbox.com/profiles/netsprint-s-a-1
In EDIT mode (not showing): http://fundingbox.com/profiles/3c1f7466a78ac7ef53e0bdbc/success
When looking at collection not showing: http://fundingbox.com/collections/hot-polish-startups

**Comment by xurxo** [comment] 2016-01-22 16:18
This is caused by a recent change in the data model and will be fixed in the next release

**Comment by xurxo** [comment] 2017-02-13 10:59
We are cleaning some old issues, so I'm closing this.
Please reopen it if the problem persist

**Closed by xurxo** 2017-02-13 10:59 UTC
Labels: bug
