### ISSUE TITLE
Spaces logs you off

### ISSUE THREAD

**Issue by SanyuKarani** [Cores-ts/Fundingbox-support#75] opened 2016-07-04 09:37 UTC
Once you hit to reply in spaces after accessing a direct contact from a collection and you try to reply it logs you off

**Comment by xurxo** [comment] 2016-07-05 06:35
This was probably caused by a server connectivity problem, not the app itself so I'm closing this issue and keep alert if happen again.

**Closed by xurxo** 2016-07-05 06:35 UTC
Labels: wontfix
