### ISSUE TITLE
I can not login

### ISSUE THREAD

**Issue by adymowska** [Cores-ts/Fundingbox-support#70] opened 2016-07-04 08:47 UTC
Clicking Login or signup the next page is "not available".

**Comment by xurxo** [comment] 2016-07-05 06:42
I think it was some kind of server shortage, so please try again and close the issue if it's working

**Comment by adymowska** [comment] 2016-07-06 07:00
Hi Jorge,

Unfortunately still the same.

Tomorrow I have the meeting with my team, and I would like to present them
FBOX 4.0…. I hope you will solve this issue.



And the second thing. Please check is I have an administrator account. I
would like to start testing , dashboard, calls etc.

THX



Best regards,

Anna Dymowska



*From:* Jorge Fernández [mailto:notifications@github.com]
*Sent:* Tuesday, July 05, 2016 8:43 AM
*To:* Cores-ts/Fundingbox-support <Fundingbox-support@noreply.github.com>
*Cc:* adymowska <anna.dymowska@fundingbox.com>; Author <
author@noreply.github.com>
*Subject:* Re: [Cores-ts/Fundingbox-support] I can not login (#70)



I think it was some kind of server shortage, so please try again and close
the issue if it's working

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cores-ts/Fundingbox-support/issues/70#issuecomment-230398820>,
or mute the thread
<https://github.com/notifications/unsubscribe/AQO8imTIP8hcPq0SKBNxsyuU2vV7VGl7ks5qSfzfgaJpZM4JEKvo>
.[image: Obraz usunięty przez nadawcę.]

**Comment by xurxo** [comment] 2016-07-06 07:19
I'm not able to reproduce this, please attach a screenshot with the error page

**Comment by adymowska** [comment] 2016-07-06 07:24
OMG. Now is OK.



I will come back if the issue appear again.



Thank you,

Anna Dymowska



*From:* Jorge Fernández [mailto:notifications@github.com]
*Sent:* Wednesday, July 06, 2016 9:19 AM
*To:* Cores-ts/Fundingbox-support <Fundingbox-support@noreply.github.com>
*Cc:* adymowska <anna.dymowska@fundingbox.com>; Author <
author@noreply.github.com>
*Subject:* Re: [Cores-ts/Fundingbox-support] I can not login (#70)



I'm not able to reproduce this, please attach a screenshot with the error
page

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cores-ts/Fundingbox-support/issues/70#issuecomment-230697018>,
or mute the thread
<https://github.com/notifications/unsubscribe/AQO8iiR-2u_VbBBSMgrf2WELmSupfIbYks5qS1cBgaJpZM4JEKvo>
.[image: Obraz usunięty przez nadawcę.]

**Comment by xurxo** [comment] 2016-07-06 07:24
OK so I'm closing the issue

**Closed by xurxo** 2016-07-06 07:24 UTC
Labels: wontfix
